### ISSUE TITLE
renaming would be better?

### ISSUE THREAD

**Issue by Quantum-Codes** [Sid72020123/siddhesh#1]
People will be comfortable to use then xD

Is this the API one? Uhh I dont think so.,

2K DOWNLOADS?!!

**Comment by Sid72020123** [comment]
No! This is not a API one. The name is actually my real name. That library
is not a API one. I am gonna share the API one in a few days. This is one
of my oldest libraries.

**Comment by Sid72020123** [comment]
Yes it has 2K+ downloads!

**Comment by Quantum-Codes** [comment]
Wow

**Comment by Sid72020123** [comment]
Now it's 3K+

**Comment by Quantum-Codes** [comment]
Wow! What dies this do btw?

**Comment by Sid72020123** [comment]
Read it here: https://mclofqpx6tzsimuoscgzha-on.drv.tw/sidpy/
